### ISSUE TITLE
Error in postARM.log in d0 about multipathd.service not present

### ISSUE THREAD

**Issue by Jatinder-Luthra** [Azure/db2-on-azure#1]
systemctl start multipathd 
Failed to start multipathd.service: Unit not found.

device-mapper-multipath is not present on the server.

Just trying to understand at what step it is getting installed.
```
[root@d0 ~]# rpm -q device-mapper-multipath || yum install -y device-mapper-multipath
package device-mapper-multipath is not installed
```

Tried to install manually but got issue from all mirrors 
`'"SSL peer rejected your certificate as expired."`

Any help is much appreciated.

**Comment by Jatinder-Luthra** [comment]
Is there any way to restart the process after a few failures?

I manually update yum repository and install multipath service, as mentioned in link-`https://docs.microsoft.com/en-us/azure/virtual-machines/linux/update-infrastructure-redhat#manual-update-procedure-to-use-the-azure-rhui-servers`

Is there a way to restart the process from where it fails? Or a sequence of manual scripts we can follow to do rest of setup?

~Thanks

**Comment by Jatinder-Luthra** [comment]
I was able to fix this by installing multipath and iscsi utilities manually.

**Comment by Ed-Price** [comment]
Thank you. We're working on a solution to improve our documentation.
