### ISSUE TITLE
Unable to create DB2 pureScale instance

### ISSUE THREAD

**Issue by Jatinder-Luthra** [Azure/db2-on-azure#2]
Error while DB2 Instance creation step, while running this

/data2/db2bits/server_dec/db2setup -r /root/db2server.rsp -l /tmp/db2setup_000.log -t /tmp/db2setup_000.trc

I tried the solution in https://github.com/Azure/db2-on-azure/blob/master/doc/archive/KB_archive.md but it still gives the same error.

Installing DB2 file sets :.......Success 
Installing or updating DB2 HA scripts for IBM Tivoli System Automation for Multiplatforms (Tivoli SA MP) :.......Success 
Installing or updating DB2 Cluster Scripts for IBM Spectrum Scale (GPFS) :.......Success 
Compiling GPL :.......Success 
Executing control tasks :.......Success 
Updating global registry :.......Success 
Updating the db2ls and db2greg link :.......Success 
Setting default global profile registry variables :.......Success 
Register NTP :.......Success 
Initializing instance list :.......Success 
Initiating the remote host list :.......Success
```
ERROR: A reachable IP address could not be automatically determined that did
not belong to one of the hosts in the DB2 pureScale instance. There may be a
problem with the network adapters gateway IP address or with the hosts network
connection. Verify connectivity for the hosts and manually edit the
configuration file /var/ct/cfg/netmon.cf on each host to include an IP on the
network outside of the DB2 pureScale instance that can be reached by the ping
command so that DB2 may ensure network connectivity. Hosts: "d0  d1 cf0 cf1".
The format of /var/ct/cfg/netmon.cf lines is as follows:  !REQD eth1
9.26.123.245
```
Configuring DB2 instances :.......Failure 
Registering DB2 Update Service :.......Success 
Updating global profile registry :.......Success 
WARNING: A minor error occurred while installing "DB2 Server Edition " on this
computer. Some features may not function correctly.

**Comment by Ed-Price** [comment]
Thank you. We're working on a solution to improve our documentation. Ultimately, the witness should be on the admin network, it's recommended that you don't need/use the witness, and you can ignore this error message (if you do get it... which the goal is to avoid it). The updates in the documentation will add a lot more additional clarity and information. Thank you for your help, as we seek to make this a frictionless process!

**Comment by Jatinder-Luthra** [comment]
Thanks @EdPrice-MSFT for comment. Witness node comes as part of the setup. 
Due to this error, we are not able to create a DB2 instance. I am really stuck at this point from last few weeks.
Any help is appreciated here, on how to proceed.

**Comment by Jatinder-Luthra** [comment]
I got confirmation from IBM support that this is not a supported procedure/environment, as the use of GlusterFS under GPFS is known to be susceptible to data corruption.

They also communicated to MS team that this document be taken down, or at minimum marked as experimental and unsupported by IBM.

**Comment by Ed-Price** [comment]
IBM recommends using Storage Spaces Direct. This shouldn't have the witness issue. We'll update the documentation with more information about this topic, as well as with the SSD instructions. The existing scenario works fine, but we'll add clarity around this scenario. Thank you.

**Comment by Ed-Price** [comment]
We updated the Docs pages with that information: 

     https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ibm-db2-purescale-azure
     https://docs.microsoft.com/en-us/azure/virtual-machines/linux/deploy-ibm-db2-purescale-azure

Thanks!
